version: "3"

services:
  snaker:
    restart: on-failure
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: snaker-1
    image: snaker-1
    ports:
     - "8080:8080"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    expose:
      - 9090
    volumes:
      - "./prometheus:/etc/prometheus"
    depends_on:
      - snaker

  grafana:
    image: grafana/grafana
    links:
      - prometheus:prometheus # datasource = http://prometheus:9090
    ports:
      - 3000:3000
    user: "104"

    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global
    depends_on:
      - grafana

